### PR TITLE
Don't allow public IPs to request monitoring endpoints

### PR DESCRIPTION
**Pull request by spmason**
This still allows through requests from 'private' IPs - 10.x, localhost etc

### CODE REVIEW

**Comment by stefanbuck** [comment]
@spmason do you remember the reason for that change? The PR deployments are using the /healthz endpoint to check whether or not the app is ready to serve traffic. There is also /status which seems to still work in prod. Maybe best to just run the check against the login page anyway.

**Comment by spmason** [comment]
I believe this was raised in a security audit..

**Comment by spmason** [comment]
Doesn't the PR deployment stuff use internal IPs to do healthchecks?

**Comment by stefanbuck** [comment]
> Doesn't the PR deployment stuff use internal IPs to do healthchecks?

Good point. This might be the case for jobs running on Jenkins, but now that we have jobs also in GitHub Actions it might not work. Anyway, I updated the script to use the login page instead of this `/healtz` endpoint

**Pull request merged**
